#!/bin/bash
set -eo pipefail

app_path="$(readlink -f "${0}")"
HERE="$(dirname "${app_path}")"

export QT_PROPORTIONAL_FONTS=1
export QT_QPA_PLATFORMTHEME="xdgdesktopportal"

export LD_LIBRARY_PATH="${HERE}/usr/lib:${LD_LIBRARY_PATH}"
export QT_PLUGIN_PATH="${HERE}/usr/plugins"

exec "${HERE}/usr/bin/showbox-studio" "$@"
